### PR TITLE
Major rewrite of TCPShield

### PR DESCRIPTION
**Pull request by paulzhng**
## TCPShield rewrite

This PR includes drastic changes to the TCPShield plugin. In order to understand the changes, I am going through most of them, and explain the works and motives behind them.

### Gradle
This rewrite includes a move from Maven to Gradle.

1. automatic versioning (see later) 
2. less boilerplate code
3. faster compile times

### Versioning
Through the usage of GSON and SnakeYAML during build time, the plugin "manifest" files `plugin.yml`, `bungee.yml` and `velocity-plugin.json` are always up-to-date.

This reduces risks of wrong version numbers and time needed to update the version itself.

The version is updated by changing the variable `version` in `build.gradle` to the new version. 
For example: `version = '1.8'` -> `version = '2.0'`.

### Abstraction
Abstraction is the logical way to implement support for more than one platform. In order to reduce duplicate code, the main business logic is contained in classes shared by all platforms.
Abstraction also allows easy creation of tests.

The "heart" of the logic lies in `net.tcpshield.tcpshield.HandshakePacketHandler`.
There are three interfaces / abstract classes which handle platform specific tasks like e.g. modifying the original packet, setting their ip, configuration, etc.

In order to implement a new platform, one needs to implement `IPlayer`, `IPacket` and `TCPShieldConfig`. An example of an implementation of those classes can be seen under `net.tcpshield.tcpshield.bungee.impl`.

The second step is going through the usual steps in developing a plugin native for the platform: e.g. create a main class, create the plugin "manifest" (don't forget to add auto-versioning for that file in `build.gradle`!)

The final step is to implement packet interception and forwarding it to `HandshakePacketHandler`. An example of that can be seen in `net.tcpshield.tcpshield.bungee.BungeeHandshakePacketHandler`.

I encourage you to put platform-specific code in a package specific to that platform in order to retain a neat & tidy structure.

### Exceptions
In order to improve code quality, there are custom exceptions specific for TCPShield. The exception handling is done in `net.tcpshield.tcpshield.HandshakePacketHandler`. Most exceptions don't get printed to the console unless `debug` is enabled in the config.

### Testing
This rewrite includes JUnit 5 Tests in order to catch bugs early in the process. All tests are executed on build time.

Testing is yet limited to platform-independent code. Further tests for platform-specific code should be added in the future.

#### Native Paper support
Because Paper provides the `PlayerHandshakeEvent`, we are able to easily implement native support. With only around 130 lines of code, some code-sharing with the ProtocolLib implementation and **no use of Reflection** (except maybe the check if the server is Paper), maintaining native Paper support is easy and straightforward.

#### Velocity support
Originally implemented as a demonstration of the benefits of abstraction, including Velocity support increases the target group able to enjoy TCPShield.

 ### New Timestamp Validation
Time Validation was oddly enough originally only implemented in the Bungee version of TCPShield. In order to guarantee integrity of the received data, timestamp validation is crucial. 

The downside of timestamp validation is that many admins don't have access to the host machine. Server times off by ~3 seconds render TCPShield with timestamp validation unusable.

The rewrite includes three configurable modes regarding timestamp validation:
1. HTPDate (default): syncs server time with a HTTP request to google.com (HTTP responses include the server time)
2. System Time: uses the system time
3. Disabled: disables timestamp validation (*really really* not recommended to use)

### CODE REVIEW

**Comment by ghost** [comment]
@Fuzzlemann Absolutely fantastic work here!

This will take me sometime to review, I may have a few comments before we merge into master. I was only able to glance today.

I will do a full review sometime over the next 48 hours.

Thanks so much for your contribution. This will do much for the MC community.

**Comment by nuriofernandez** [comment]
Nice work, but maybe it fails about keeping things simple. 😄💭

**Comment by paulzhng** [comment]
Personally don't see another way it could be done easier and with the same amount of encapsulation / abstraction providing the same amount of flexibility and ease of porting.

**Review by nuriofernandez — APPROVED** [review]

**Review by nuriofernandez — APPROVED** [review]
Nice one!!
Be careful with this class, it can lock the thread during DNS resolve.

**Pull request merged**
